[ids]
3299:4e52:adce41bd
25a7:fa70:6e440587
#BT 5.0KB
000e:3412
# CM Storm Quick Fire XT
2516:001a
[main]
capslock = overload(control, esc)
#tab = overload(shift, tab)
#mouse1 = overload(alt, mouse1)
leftalt = leftmeta
leftmeta = leftalt
