set -g mouse on

# prefix
set -g prefix C-space
bind-key C-space send-prefix

# splits
# bind | split-window -h
# bind - split-window -v
# new panes in cwd
bind - split-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# new window
bind o new-window -c "#{pane_current_path}"
bind O new-window

# next pane
#bind N select-pane -t:+ 

# recent window
#bind Tab select-window -ta:!


# vim pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# bind C-h select-window -t :-
# bind C-l select-window -t :+

# colors
# Colors for pane borders
# set -w -g pane-border-style fg=green,bg=black
# set -w -g pane-active-border-style fg=black,bg=yellow

# reload config
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display-message "Configuration reloaded!"

# shift+return fix
set -g extended-keys on
set -g extended-keys-format csi-u

# cursor fix
set -g allow-passthrough on
#set -ga terminal-features ",xterm-ghostty:cstyle"


